import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/personal/Navbar";
import Footer from "@/components/personal/Footer";
import { cookies, headers } from "next/headers";
import { connection } from "next/server";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const ck = await cookies(); // ✅ Await the cookies
  const user = ck.get("user");
  const name = user ? JSON.parse(user.value).name : undefined;
  await connection()
  

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster />
          <NextTopLoader color="#db6216"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3} />
          <Navbar name={(name) ? "Hi, " + name : undefined} />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
