import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/personal/Navbar";
import Footer from "@/components/personal/Footer";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  const ck = await cookies(); // ✅ Await the cookies
  const user =  ck.get("user");
  const name = user ? JSON.parse(user.value).name : undefined;
  

  return (
    
      <>
        {children}
      </>
   
  );
}
